(function(d){var b=window.AmazonUIPageJS||window.P,e=b._namespace||b.attributeErrors,c=e?e("PortableOffersDisplayAssets@core","PortableOffersDisplayAssets"):b;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,b,e){d.when("ax:initiator","action-handler:dom-input-parser").register("cta-handler",function(c,b){function a(a){c.initiateCTAHandling(a,(1<arguments.length&&arguments[1]!==e?arguments[1]:null)||b.createRequestPayload(a))}return{handleATCClick:a,handleCTAClick:a}});
"use strict";d.register("pcta:bottom-sheet-constants",function(){return{EVENTS:{AFTER_SHOW:"a:sheet:afterShow:",AFTER_HIDE:"a:sheet:afterHide:"}}});"use strict";d.register("pcta:utils:csm",function(){function c(a,c){b.ue&&b.ue.count&&b.ue.count(a,c)}function g(){try{var a=document.querySelector('input[name\x3d"referrer"]');return a&&a.value?a.value.trim():"unknownPageType"}catch(k){return"pageType:extraction:error"}}return{logCounter:c,logPerformance:function(a){performance&&performance.now&&c(a,
b.parseInt(performance.now()))},logCounterWithPageContext:function(a,b){var d=g();c(a+":"+d,b)},logPerformanceWithPageContext:function(a){var d=g();if(performance&&performance.now){var f=b.parseInt(performance.now());c(a+":"+d,f)}},getPageTypeForMetrics:g}});"use strict";d.register("action-handler:dom-input-parser",function(){return{createRequestPayload:function(c){var b={};var a=c.$target.attr("form");a=document.getElementById(a);var d=c.$target.closest("form");if(a=a?a:0<d.length?d[0]:null){d=a.elements;
for(var f=0;f<d.length;f++){var e=d[f];e.name&&(b[e.name]=e.value)}(a=a.getAttribute("action")||a.action)&&(b.formAction=a)}c=c.data;for(var h in c)c.hasOwnProperty(h)&&(b[h]=c[h]);return b}}});"use strict";d.register("pcta:utils:iframe",function(){return{isIframe:function(){return b!==b.parent},isCTAHandlerOnParentWindow:function(){if(this.isIframe()&&b.parent&&b.parent.P){var c=!1;b.parent.P.now("cta-handler").execute(function(b){c=!!b});return c}return!1}}})});
/* ******** */
'use strict';(function(x){var v=window.AmazonUIPageJS||window.P,A=v._namespace||v.attributeErrors,C=A?A("PortableVariableWeightAssets",""):v;C.guardFatal?C.guardFatal(x)(C,window):C.execute(function(){x(C,window)})})(function(x,v,A){function C(g){var d=!1;x.now(g).execute("pvwDuplicationGuard",function(h){d=!!h});return d}function ca(g,d){if(!C(g))try{x.register(g,d)}catch(h){if(!h.message.includes("reregistered by PortableVariableWeightAssets"))throw h;}}function ha(){var g=arguments;return{register:function(d,
h){if(!C(d))try{x.when.apply(x,g).register(d,h)}catch(f){if(!f.message.includes("reregistered by PortableVariableWeightAssets"))throw f;}},execute:function(d,h){x.when.apply(x,g).execute(d,h)}}}function Ka(g,d){if(!g)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!d||"object"!==typeof d&&"function"!==typeof d?g:d}function La(g,d){if("function"!==typeof d&&null!==d)throw new TypeError("Super expression must either be null or a function, not "+typeof d);
g.prototype=Object.create(d&&d.prototype,{constructor:{value:g,enumerable:!1,writable:!0,configurable:!0}});d&&(Object.setPrototypeOf?Object.setPrototypeOf(g,d):g.__proto__=d)}function Aa(g,d){if(!(g instanceof d))throw new TypeError("Cannot call a class as a function");}ca("PVWDuplicationGuard",function(){return{register:ca,when:ha}});"use strict";x.when("PVWDuplicationGuard").execute("pvw-constants-registration",function(g){g.register("pvw-constants",function(){return{ITEM_HEIGHT:40,SCROLL_DELAY:100,
SHEET_HEIGHT:355,SHEET_NAME:"pvw_bottom_sheet",DECIMAL_SEPARATOR:".",PRECISION_DEFAULT:2,MODE:{ATC:"atc",ATD:"atd"},UNITS:{GRAMS:"GRAMS",KILOGRAMS:"KILOGRAMS",OUNCES:"OUNCES",POUNDS:"POUNDS",GRAM_SYMBOL:"g",POUND_SYMBOL:"lb",KILOGRAM_SYMBOL:"kg",OUNCES_SYMBOL:"oz",UNIT_SYMBOL_MAP:{GRAMS:"g",KILOGRAMS:"kg",OUNCES:"oz",POUNDS:"lb"}},METRICS:{SHOW_POPUP:"showPopup",TRIGGER_DECLARATIVE_ACTION:"triggerDeclarativeAction"},SUCCESS:!0,FAILURE:!1,MOBILE:!0,DESKTOP:!1,PVW_CONTAINER:".vw-container",PVW_REPLACE:".pvw-replace",
TEMPLATE_VERSION:{V1:"V1",V2:"V2"},TEMPLATE_REPLACE_STRING:{QUANTITY:"{quantity}",ESTIMATE:"{estimate}",REPLACE:"{replace}"}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-bottom-sheet-registration",function(g){g.when("A","a-sheet","portable-variable-weight-view-model","pvw-state-factory","pvw-content-manager","pvw-constants","pvw-bs-translations","pvw-csm-util").register("pvw-bottom-sheet",function(d,h,f,g,n,c,p,z){function t(c){q.currentQuantity=c}var q=null,w=null,L=d.now();z.logLatencyMetric("-JSReady",
L,c.MOBILE);return{openSheet:function(t,U){d.$(".a-sheet-lightbox").click();d.on("a:sheet:afterHide",function J(h){h.sheet._name!==c.SHEET_NAME&&(w=h.sheet);d.off("a:sheet:afterHide",J)});setTimeout(function(){try{q=g.createInitialState(t,U);var d=f.getMobileContent(q),w=h.get(c.SHEET_NAME);if(w)n.setContent(w.getContentContainer(),d);else{var V={name:c.SHEET_NAME,inlineContent:d,height:c.SHEET_HEIGHT};q.templateVersion===c.TEMPLATE_VERSION.V2?(V.closeType="icon",V.heading=p.selectQuantityText):(V.closeType=
"message",V.closeMessage=p.cancelMessage);var y=h.create(V);z.incrementInitializeCount(!0,!0);w=y}h.showSheet(w)}catch(u){throw z.incrementShowPopup(c.FAILURE,c.MOBILE),u;}z.incrementShowPopup(c.SUCCESS,c.MOBILE)})},afterSheetShow:function(c){n.cacheElements(c.sheet.$contentContainer);n.selectItem(q.currentQuantity,q);n.setupScrollHandler(q,t)},handleSheetClose:function(){var f=h.get(c.SHEET_NAME);n.removeAllContent(f.getContentContainer());q=null;w&&(d.trigger("pvw-bottom-sheet:afterClosed",{previousSheetName:w._name}),
w=null)},handleATCClick:function(d){d.$event.preventDefault();try{q.ctaButtonClickCallback(q.currentQuantity),h.hideSheet(h.get(c.SHEET_NAME))}catch(Ma){throw z.incrementTriggerDeclarativeActionCount(d.action,c.FAILURE,c.MOBILE),Ma;}z.incrementTriggerDeclarativeActionCount(d.action,c.SUCCESS,c.MOBILE)},getAUISheetName:function(){return c.SHEET_NAME}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-drop-down-registration",function(g){g.when("A","a-dropdown","portable-variable-weight-view-model",
"pvw-state-factory","pvw-constants","pvw-csm-util","pvw-weight-utils","pvw-pricing-utils","pvw-bs-translations","pvw-dropdown-footer").register("pvw-drop-down",function(d,h,f,g,n,c,p,z,U,q){function w(c,f,n){var p="a:popover:hide:"+n;d.on("a:dropdown:popover:open:pvw-dropdown-"+n,function(c){c=c.closest(".a-popover");h.setFooterContent(c,q.createFooterFragment())});d.on(p,function(d){x(c,f)})}function t(c,h,f,n){var p="a:dropdown:selected:"+f;d.off(p);d.on(p,function(f){n(parseFloat(f.value));x(c,
h);d.off(p)})}function x(c,d){d.hide();c.show();c=c.find('[role\x3d"combobox"]');c.length&&c.focus()}function v(c,d){d=U.aboutLowerCase.replace(n.TEMPLATE_REPLACE_STRING.ESTIMATE,d);return{html:c+' \x3cspan class\x3d"a-color-tertiary"\x3e'+d+"\x3c/span\x3e",text:c+" "+d}}function A(c){C=g.createInitialState(c,null);var d=c.estimateAverageSizeUnitOfMeasureUnit?p.getWeightUnitSymbol(c.estimateAverageSizeUnitOfMeasureUnit):p.getWeightUnitSymbol(c.pricingUnitOfMeasureUnit);return C.selectorValues.map(function(h,
f){if(c.isItemSoldByCount){var q=C.selectorValues.at(f);q=v(q,p.formatWeight(c.estimateAverageSize*q,d,n.PRECISION_DEFAULT,c.decimalSeparator))}else{q=C.selectorDisplayValues.at(f);var g=C.selectorValues.at(f);f=z.isNonFractionalCurrency(c.currencyCode||c.pricePerUnitMoneyCurrencyCode);g=z.calculatePrice(c.pricePerSingleUnitAmount,g,f);f=z.formatPriceForDisplay(g,c.currencySymbol,f,c.currencySymbolPosition||"Left",c.decimalSeparator);q=v(q,f)}return{value:h,displayValue:q.html,displayText:q.text}})}
var C=null,J=d.now();c.logLatencyMetric("-JSReady",J,n.DESKTOP);return{openDropdown:function(c,n,p,q,g){0==q.length?(q=A(c),q=d.$(f.getDesktopContent({asin:g,selectedOption:c.currentQuantity,dropdownOptions:q})),p.parent().prepend(q),w(p,q,g)):(c=c.currentQuantity)&&q&&h.getSelect(q.find("select.a-native-dropdown")).setValue(c);t(p,q,g,n);n=q;n.show();p.hide();n.find("select.a-native-dropdown").click()}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-dropdown-footer-registration",function(g){g.when("pvw-bs-translations").register("pvw-dropdown-footer",
function(d){return{createFooterFragment:function(){var h=new DocumentFragment,f=document.createElement("div");f.className="pvw-dropdown-footer-inner";var g='\x3cspan\x3e\x3cdiv class\x3d"a-color-secondary a-text-bold"\x3e'+d.variableWeightDisclaimer.replace(/\./,"")+"\x3c/div\x3e\x3c/span\x3e";f.innerHTML=g;h.append(f);return h}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-expanded-stepper-registration",function(g){g.when("pvw-text-replace").register("pvw-expanded-stepper",function(d){return{setExpandedStepperWithRegulatoryText:function(h,
f,g,n){if(n&&h.setValueWithStepperDisplays){var c="true"===h.getElement().dataset.shouldCondenseRegulatoryText;n=d.createRegulatoryDisplayDocumentFragment(g,n,c);h.setValueWithStepperDisplays(g,f,n)}else h.setValueWithDisplayString(g,f)}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-state-factory-registration",function(g){g.when("pvw-weight-utils","pvw-bs-translations","pvw-constants","pvw-text-replace").register("pvw-state-factory",function(d,h,f,g){function n(c){return c.map(function(c){c=
1===c?h.itemText.replace(f.TEMPLATE_REPLACE_STRING.QUANTITY,c):h.itemsText.replace(f.TEMPLATE_REPLACE_STRING.QUANTITY,c);return c})}return{createInitialState:function(c,p){var z=c.sellingMax,t=c.sellingIncrement,q=[],w=c.sellingMin;if(Number.isFinite(t)&&!(0>=t))for(;w<=z;)q.push(w),w+=t,w=parseFloat(w.toFixed(2));z=d.getWeightUnitSymbol(c.pricingUnitOfMeasureUnit||c.sellingUnitOfMeasureUnit);w=c.currencySymbolPosition&&"right"===c.currencySymbolPosition.toLowerCase()?"Right":"Left";var L=c.currentQuantity||
c.sellingMin||1;t=c.templateVersion||f.TEMPLATE_VERSION.V2;var x=c.mode||f.MODE.ATC;if(x===f.MODE.ATD){var v=c.decimalSeparator;var A=L.toFixed(1);v&&"."!==v&&(A=A.replace(".",v));v=h.addToDeliveryButtonText.replace("{qty}",A).replace("{unit}",z)}else v=c.currentQuantity?t===f.TEMPLATE_VERSION.V2?h.updateQuantityText:h.updateCartButtonText:h.addToCartButtonText;p={isItemSoldByCount:c.isItemSoldByCount,currentQuantity:L,selectorValues:q,pricePerUnitAmount:c.pricePerSingleUnitAmount,pricePerUnitDisplayString:c.pricePerUnitDisplayString,
priceSymbol:c.currencySymbol,pricingUnitOfMeasureUnit:c.pricingUnitOfMeasureUnit,currencySymbolPosition:w,currencyCode:c.pricePerUnitMoneyCurrencyCode,priceDecimalSeparator:c.decimalSeparator,ctaButtonClickCallback:p,itemWeightUnit:z,asinImageUrl:c.imageUrl,isSoldByUnit:c.isItemSoldByCount,summaryDisclaimerText:h.summaryDisclaimerText,selectQuantityText:h.selectQuantityText,summaryAtcButtonText:v,estSingleItemWeight:c.estimateAverageSize,estimateAverageSizeUnitOfMeasureUnit:c.estimateAverageSizeUnitOfMeasureUnit,
sellingMin:c.sellingMin,estTotalPriceText:h.estTotalPriceText,disclaimerText:h.variableWeightDisclaimer,aboutEstimationText:g.generateAboutEstimationText(L,c),templateVersion:t,mode:x};c.isItemSoldByCount?(p.quantitySelectorUnitText=h.quantitySelectorUnitText,p.selectorDisplayValues=t===f.TEMPLATE_VERSION.V2?n(q):q,p.estTotalWeightText=h.estTotalWeightText):p.selectorDisplayValues=d.formatWeightsForDisplay(q,z,f.PRECISION_DEFAULT,p.priceDecimalSeparator);return p}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-content-manager-registration",
function(g){g.when("A","pvw-pricing-utils","pvw-weight-utils","pvw-constants","pvw-text-replace").register("pvw-content-manager",function(d,h,f,g,n){function c(c,d){var q=d.selectorValues.indexOf(c);if(-1!==q){(d.templateVersion===g.TEMPLATE_VERSION.V2?p.pickerV2:p.picker).scrollTop(q*g.ITEM_HEIGHT);q=h.isNonFractionalCurrency(d.currencyCode);var w=f.calculateEstWeight(c,d.estSingleItemWeight,d.isItemSoldByCount),t=h.calculatePrice(d.pricePerUnitAmount,w,q);d.isItemSoldByCount&&p.estItemWeight.html(w);
p.priceWhole.html(t.whole);q?p.priceFraction.html(""):p.priceFraction.html(10>t.fraction?"0"+t.fraction:t.fraction);d.templateVersion===g.TEMPLATE_VERSION.V2&&(c=n.generateAboutEstimationText(c,{estimateAverageSize:d.estSingleItemWeight,currencySymbol:d.priceSymbol,pricePerSingleUnitAmount:d.pricePerUnitAmount,sellingMin:d.sellingMin,isItemSoldByCount:d.isItemSoldByCount,pricingUnitOfMeasureUnit:d.pricingUnitOfMeasureUnit,currencySymbolPosition:d.currencySymbolPosition,pricePerUnitMoneyCurrencyCode:d.currencyCode,
decimalSeparator:d.priceDecimalSeparator,estimateAverageSizeUnitOfMeasureUnit:d.estimateAverageSizeUnitOfMeasureUnit}),p.aboutEstText.html(c))}}var p;return{setContent:function(c,d){c.html(d)},cacheElements:function(c){p={picker:c.find(".pvw-scroll-picker"),estItemWeight:c.find(".pvw-bs-item-weight"),priceWhole:c.find(".a-price-whole"),priceFraction:c.find(".a-price-fraction"),aboutEstText:c.find(".pvw-about-est-text"),pickerV2:c.find(".pvw-scroll-picker-v2")};p.pickerV2&&p.pickerV2.length&&(p.pickerV2.find(".pvw-scroll-picker-item-v2").first().attr("aria-selected",
"true"),d.$(".a-sheet-heading").attr("id","a-sheet-heading-id"),p.pickerV2.attr("aria-labelledby","a-sheet-heading-id"))},setupScrollHandler:function(d,h){var f=void 0,n=d.templateVersion===g.TEMPLATE_VERSION.V2?p.pickerV2:p.picker;n.scroll(function(){clearTimeout(f);f=setTimeout(function(){var f=n.scrollTop();f=Math.round(f/g.ITEM_HEIGHT);var q=d.selectorValues[f];q!==A&&(c(q,d,h),h(q),p.pickerV2&&p.pickerV2.length&&p.pickerV2.find(".pvw-scroll-picker-item-v2").removeAttr("aria-selected").eq(f).attr("aria-selected",
"true"))},g.SCROLL_DELAY)})},selectItem:c,removeAllContent:function(c){c.empty()}}})});"use strict";var M=function(){return function(g,d){if(Array.isArray(g))return g;if(Symbol.iterator in Object(g)){var h=[],f=!0,t=!1,n=A;try{for(var c=g[Symbol.iterator](),p;!(f=(p=c.next()).done)&&(h.push(p.value),!d||h.length!==d);f=!0);}catch(z){t=!0,n=z}finally{try{if(!f&&c["return"])c["return"]()}finally{if(t)throw n;}}return h}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),
Ba=function(){function g(d,h){for(var f=0;f<h.length;f++){var g=h[f];g.enumerable=g.enumerable||!1;g.configurable=!0;"value"in g&&(g.writable=!0);Object.defineProperty(d,g.key,g)}}return function(d,h,f){h&&g(d.prototype,h);f&&g(d,f);return d}}(),la="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(g){return typeof g}:function(g){return g&&"function"===typeof Symbol&&g.constructor===Symbol&&g!==Symbol.prototype?"symbol":typeof g};x.when("PVWDuplicationGuard").execute("portable-variable-weight-view-model-registration",
function(g){g.register("portable-variable-weight-view-model",function(){var d;(function(){function g(b,a,m,r){return b.substring(0,a)+r+b.substring(m)}function f(b){if(!b||!b.styleCodeString||1>b.styleCodeArray.length)return!1;var a=!1;return b.styleCodeArray.every(function(b){return""===b||"."===b||!!function(a){return Oa.some(function(b){return a.startsWith(b)})}(b)&&(!a&&function(a){return ma.some(function(b){return a.startsWith(b)})}(b)&&(a=!0),!0)})&&a}function t(b){var a=Pa.exec(b);if(a&&a[0]&&
a[1]&&a[2]&&a[3]&&a[1].startsWith("images/"))return{sourceUrl:b,path:a[1],styleCodeString:a[2],styleCodeArray:a[2].split("_"),extension:a[3],queryString:a[4]}}function n(b,a,m){return b.queryString?a+"\x26aicid\x3d"+m:a+"?aicid\x3d"+m}function c(b){switch(b){case "Unspecified":return"unspecified";case "Normal":return"normal";case "Selected":return"selected";case "Disabled":return"disabled";case "Error":return"error";case "Warning":return"warning";case "Inactive":return"inactive";default:return b}}
function p(b){switch(b){case "Unspecified":return"unspecified";case "Left":return"left";case "Right":return"right";case "Center":return"center";default:return b}}function z(b){switch(b){case "TriggerRight":return"triggerRight";case "TriggerLeft":return"triggerLeft";case "TriggerBottom":return"triggerBottom";case "TriggerTop":return"triggerTop";case "TriggerVertical":return"triggerVertical";case "TriggerHorizontal":return"triggerHorizontal";case "TriggerVerticalAlignLeft":return"triggerVerticalAlignLeft";
default:return b}}function x(b){switch(b){case "Button":return"button";case "Submit":return"submit";case "Reset":return"reset";default:return b}}function q(b){switch(b){case "Unspecified":return"unspecified";case "Thumbnail":return"thumbnail";case "Supplemental":return"supplemental";case "Dropdown":return"dropdown";default:return b}}function w(b){switch(b){case "Unspecified":return"unspecified";case "First":return"first";case "Last":return"last";case "OnlyChild":return"onlychild";default:return b}}
function L(b){switch(b){case "Unspecified":return"unspecified";case "None":return"none";case "Micro":return"micro";case "Mini":return"mini";case "Small":return"small";case "Base":return"base";case "Medium":return"medium";case "MediumPlus":return"medium-plus";case "Large":return"large";case "ExtraLarge":return"extra-large";case "ExtraLargePlus":return"extra-large-plus";case "DoubleLarge":return"double-large";case "Block":return"block";default:return b}}function v(b){switch(b){case "Unspecified":return"unspecified";
case "Micro":return"micro";case "Mini":return"mini";case "Small":return"small";case "Base":return"base";case "Medium":return"medium";case "MediumPlus":return"medium-plus";case "Large":return"large";case "ExtraLarge":return"extra-large";case "ExtraLargePlus":return"extra-large-plus";default:return b}}function C(b){switch(b){case "Unspecified":return"unspecified";case "ButtonBesideText":return"button-beside-text";default:return b}}function ca(b){switch(b){case "Unspecified":return"unspecified";case "Primary":return"primary";
case "Search":return"search";case "BuyNow":return"buynow";case "BuyNowPreorder":return"buynow-preorder";case "Cart":return"cart";case "OneClick":return"oneclick";case "OneClickPreorder":return"oneclick-preorder";case "Preorder":return"preorder";case "Sns":return"sns";case "Thumbnail":return"thumbnail";case "Toggle":return"toggle";case "ToggleUnavailable":return"toggle-unavailable";default:return b}}function ha(b){return null!=b&&""!==b}function J(b){b=b.join(" ").split(" ").filter(ha).join(" ");return 0<
b.length?b:void 0}function V(b,a){var m={},r;for(r in a+="-",b){var k=b,c=r;(k.hasOwnProperty?k.hasOwnProperty(c):k.containsKey(c))&&r.startsWith(a)&&(m[r.slice(a.length)]=b[r])}return m}function y(b,a,m){if(m){var r=m.hasOwnProperty?Object.keys(m):!(k=m.keySet()).map&&Java.from?Java.from(k):k;for(k=0;k<r.length;k++)b[a+r[k]]=m[r[k]]}var k;return b}function u(b,a){return a.content}function Na(b){return null!=b&&""!==b}function ja(b){b=b.join(" ").split(" ").filter(Na).join(" ");return 0<b.length?
b:void 0}function ka(b,a){var m={},r;for(r in a+="-",b){var k=b,c=r;(k.hasOwnProperty?k.hasOwnProperty(c):k.containsKey(c))&&r.startsWith(a)&&(m[r.slice(a.length)]=b[r])}return m}function F(b,a,m){if(m){var r=m.hasOwnProperty?Object.keys(m):!(k=m.keySet()).map&&Java.from?Java.from(k):k;for(k=0;k<r.length;k++)b[a+r[k]]=m[r[k]]}var k;return b}function Qa(b){return null!=b&&""!==b}function Ca(b,a){var m={},r;for(r in a+="-",b){var k=b,c=r;(k.hasOwnProperty?k.hasOwnProperty(c):k.containsKey(c))&&r.startsWith(a)&&
(m[r.slice(a.length)]=b[r])}return m}function na(b,a,m){if(m){var r=m.hasOwnProperty?Object.keys(m):!(k=m.keySet()).map&&Java.from?Java.from(k):k;for(k=0;k<r.length;k++)b[a+r[k]]=m[r[k]]}var k;return b}function Ra(b){switch(b){case "Unspecified":return"unspecified";case "Micro":return"micro";case "Mini":return"mini";case "Small":return"small";case "Base":return"base";case "BasePlus":return"base-plus";case "Medium":return"medium";case "MediumPlus":return"medium-plus";case "Large":return"large";case "ExtraLarge":return"extra-large";
case "DoubleLarge":return"double-large";default:return b}}function Sa(b){switch(b){case "Unspecified":return"unspecified";case "Base":return"base";case "Secondary":return"secondary";case "Tertiary":return"tertiary";case "State":return"state";case "Link":return"link";case "Inverse":return"inverse";case "Price":return"price";case "Attainable":return"attainable";case "Error":return"error";case "Warning":return"warning";case "Information":return"information";case "Success":return"success";default:return b}}
function Ta(b){switch(b){case "Unspecified":return"unspecified";case "TextBesideButton":return"text-beside-button";case "Offscreen":return"offscreen";default:return b}}function Ua(b){return null!=b&&""!==b}function Da(b,a){var m={},r;for(r in a+="-",b){var k=b,c=r;(k.hasOwnProperty?k.hasOwnProperty(c):k.containsKey(c))&&r.startsWith(a)&&(m[r.slice(a.length)]=b[r])}return m}function oa(b,a,m){if(m){var r=m.hasOwnProperty?Object.keys(m):!(k=m.keySet()).map&&Java.from?Java.from(k):k;for(k=0;k<r.length;k++)b[a+
r[k]]=m[r[k]]}var k;return b}function pa(b,a,m){if(m){var r=m.hasOwnProperty?Object.keys(m):!(k=m.keySet()).map&&Java.from?Java.from(k):k;for(k=0;k<r.length;k++)b[a+r[k]]=m[r[k]]}var k;return b}function Ea(b){switch(b){case "Unspecified":return"unspecified";case "Base":return"base";case "Secondary":return"secondary";case "Tertiary":return"tertiary";case "Price":return"price";default:return b}}function Va(b){return null!=b&&""!==b}function N(b){b=b.join(" ").split(" ").filter(Va).join(" ");return 0<
b.length?b:void 0}function D(b,a,m){if(m){var r=m.hasOwnProperty?Object.keys(m):!(k=m.keySet()).map&&Java.from?Java.from(k):k;for(k=0;k<r.length;k++)b[a+r[k]]=m[r[k]]}var k;return b}function qa(b){return b.reduce(function(a,b){return a.concat(Array.isArray(b)?qa(b):b)},[])}function Fa(b){return b instanceof Node?b.parentNode?b.cloneNode(!0):b:document.createTextNode(null==b?"":b)}function Ga(b){return b.reduce(function(a,b){return a.concat(Array.isArray(b)?Ga(b):b)},[])}function Wa(b){return b.templateVersion&&
b.templateVersion===ra.V2?Xa(sa,b,"")[0].outerHTML:Ya(sa,b,"")[0].outerHTML}function Za(b){return $a(sa,b,"")[0].outerHTML}var K={d:function(b,a){for(var c in a)K.o(a,c)&&!K.o(b,c)&&Object.defineProperty(b,c,{enumerable:!0,get:a[c]})},o:function(b,a){return Object.prototype.hasOwnProperty.call(b,a)},r:function(b){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(b,Symbol.toStringTag,{value:"Module"});Object.defineProperty(b,"__esModule",{value:!0})}},ta={};K.r(ta);K.d(ta,{getDesktopContent:function(){return Za},
getMobileContent:function(){return Wa}});var ab=new RegExp(/\d+/g),Pa=new RegExp(/(?:m\.media-amazon\.com\/|images-(?:na|eu|fe)\.ssl-images-amazon\.com\/)(.*?)(?:\.(_(?:.*)?_)\.*)?\.(jpg|jpeg)(\?.*)?/i),ma=["SX","SY","SL","SF","SR"],Oa=function(){for(var b=0,a=0,c=arguments.length;a<c;a++)b+=arguments[a].length;b=Array(b);var r=0;for(a=0;a<c;a++)for(var k=arguments[a],d=0,g=k.length;d<g;d++,r++)b[r]=k[d];return b}(ma,"AC RI FMjpg FMjpeg FMwebp TTH TTD TTW CB".split(" ")),ua={avif:{dpi1:58,dpi15:58,
dpi2:58},webp:{dpi1:65,dpi15:65,dpi2:65},jpg:{dpi1:85,dpi15:80,dpi2:80}},xa=function(){function b(){}return b.isOperationsAllowed=function(a){return f(t(a))},b.generateSrcset=function(a,b,r,c,d){var k=t(a);if(!k||!f(k))return a;a=function(a,b,r,c){function k(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];m.push.apply(m,a);e.push.apply(e,a);d.push.apply(d,a)}var m=[],e=[],d=[];k(r);a.styleCodeArray.forEach(function(b,r){if(0!==r&&r!==a.styleCodeArray.length-1||""!==b){if(""!==b&&"."!==
b){if(ma.some(function(a){return b.startsWith(a)}))return r=function(a){for(var b,e=[];b=ab.exec(a);)e.push({value:parseInt(b[0]),index:b.index,length:b[0].length});return e}(b),r=(W=c=b,f=c,h=c,r.reverse().forEach(function(a){var b=a.value,e=a.index;a=a.length;var r=Math.min(5E3,Math.round(1.5*b)),c=Math.min(5E3,2*b);W=g(W,e,e+a,(1*b).toString());f=g(f,e,e+a,r.toString());h=g(h,e,e+a,c.toString())}),{x1:W,x15:f,x2:h}),m.push(r.x1),e.push(r.x15),void d.push(r.x2);var c,W,f,h}k(b)}});m.push("QL"+ua[b].dpi1);
e.push("QL"+ua[b].dpi15);d.push("QL"+ua[b].dpi2);("jpeg"===a.extension?"jpg":a.extension)!==b&&k("FM"+b);b=a.sourceUrl.replace(a.styleCodeString,"_"+m.join("_")+"_");r=a.sourceUrl.replace(a.styleCodeString,"_"+e.join("_")+"_");var W=a.sourceUrl.replace(a.styleCodeString,"_"+d.join("_")+"_");return{x1:n(a,b,c),x15:n(a,r,c),x2:n(a,W,c)}}(k,b,"AIweblab"+r+","+c,d);b=[];return b.push(a.x1+" 1x"),a.x15!==a.x1&&b.push(a.x15+" 1.5x"),a.x2!==a.x15&&b.push(a.x2+" 2x"),b.join(", ")},b.generateCacheBuster=function(a,
b,r,c){var k=t(a);return k&&f(k)?function(a,b,r){var c=[b];return a.styleCodeArray.forEach(function(b,r){(0!==r&&r!==a.styleCodeArray.length-1||""!==b)&&c.push(b)}),n(a,a.sourceUrl.replace(a.styleCodeString,"_"+c.join("_")+"_"),r)}(k,"AIweblab"+b+","+r,c):a},b}(),Y,Ia={nbsp:" ",amp:"\x26",lt:"\x3c",gt:"\x3e",quot:'"',"#x27":"'","#x60":"`"},db=[/^([\w-]+(\.))*amazon(.(com|in|fr|de|cn|it|nl|sg|es|tr|ae))$/i,/^([\w-]+(\.))*amazon.com.(au|br|mx)$/i,/^([\w-]+(\.))*amazon.co.(uk|jp)$/i],ya=function(){function b(a){this.context=
a;this._getTreatmentRecordTriggerCache={};this._isWeblabActiveCache={};this._shouldUseWeblabCache="T1"===this.getTreatmentRecordTriggerNoCache("AUI_TEMPLATE_WEBLAB_CACHE_333406")}return b.prototype.deviceType=function(){return this.context.attributes.device_type||"Desktop"},b.prototype.getTreatmentRecordTriggerNoCache=function(a){return this.context.weblabProvider.getTreatmentRecordTrigger(a)},b.prototype.getTreatmentRecordTrigger=function(a){return this._shouldUseWeblabCache?a in this._getTreatmentRecordTriggerCache?
this._getTreatmentRecordTriggerCache[a]:this._getTreatmentRecordTriggerCache[a]=this.getTreatmentRecordTriggerNoCache(a):this.getTreatmentRecordTriggerNoCache(a)},b.prototype.variant=function(a){if(-1<a.indexOf("\x3d"))throw Error("Found \x3d in variant "+a+"-- should be a :");if(-1<this.context.variants.indexOf(a))return!0;if(-1<a.indexOf(":")){var b=a.substring(0,a.lastIndexOf(":"));a=a.substring(a.lastIndexOf(":"),a.length);return this.context.attributes[b]==a}},b.prototype.isWhiteListedUrl=function(a){var b=
function(a){if(a.startsWith("//")||-1!==a.indexOf("://"))return a.split("/",3)[2].split(":",2)[0]}(a);return!b||db.some(function(a){return a.test(b)})},b.prototype.isWeblabActive=function(a){return this._shouldUseWeblabCache?a in this._isWeblabActiveCache?this._isWeblabActiveCache[a]:this._isWeblabActiveCache[a]=this.context.weblabProvider.isActive(a):this.context.weblabProvider.isActive(a)},b.prototype.weblabClasses=function(){return""},b.prototype.weblabState=function(){return{}},b.prototype.tnr=
function(a){var b={};return"T1"==this.getTreatmentRecordTrigger("AUI_TNR_V2_180836")&&a.forEach(function(a){b["data-ux-"+a]=""}),this.normalizeTable(b)},b.prototype.decToInt=function(a){return a=+a,isFinite(a)?a-a%1||(0>a?-0:0===a?a:0):a},b.prototype.join=function(a,b){return b.join(a)},b.prototype.trim=function(a){return a.trim()},b.prototype.emptyTable=function(){return{}},b.prototype.tableOf=function(a,b){var c={};return c[a]=b,c},b.prototype.parseAttrs=function(a){for(var b={},c=/([:_A-Za-z][-:_.A-Za-z0-9]*)\s*(?:=\s*(?:"((?:[^"\\]|\\.)*)"|'((?:[^'\\]|\\.)*)'|([^ "'`=<>]+)))?/g,
k=c.exec(a);null!=k;)k=k.filter(function(a){return void 0!==a}),b[k[1]]=k[2]||"",k=c.exec(a);return this.normalizeTable(b)},b.prototype.listLength=function(a){return a.length},b.prototype.discard=function(){return""},b.prototype.normalizeTable=function(a){return Object.keys(a).sort().reduce(function(b,c){return b[c]=a[c],b},{})},b.prototype.convertCarouselOptions=function(a){var b="ajax fetch_delay url id_list id_list_param_name animating animation_speed auto_adjust_height circular currentGutter firstVisibleItem first_item_flush_left height_animation_speed hide_off_screen loading maintain_state maxHeight minimum_gutter_width pageNumber pageSize px set_size show_partial_next single_page_align totalPages wrap_easing".split(" "),
c={},k;for(k in a){var d=k.replace(/[\w]([A-Z])/g,function(a){return a[0]+"_"+a[1]}).toLowerCase(),f=a[k];f=Array.isArray(f)||"object"!=("undefined"===typeof f?"undefined":la(f))?f:this.convertCarouselOptions(f);0<=b.indexOf(d)?c[d]=f:c[k]=f}return c},b.prototype.encodeAttrs=function(a){return Object.keys(a).reduce(function(b,c){return"string"==typeof a[c]?b[c]=a[c]:void 0===a[c]||null===a[c]?b[c]="":b[c]=JSON.stringify(a[c]),b},{})},b.prototype.unescapeHtml=function(a){return a.replace(/&([#a-z0-9]+);/gi,
function(a,b){return Ia[b]?Ia[b]:(b=b.match(/^#x([\da-f]+)$/i))?String.fromCharCode(parseInt(b[1],16)):a})},b.prototype.formatDecimal=function(a){return(Math.round(100*a)/100).toString()},b.prototype.needAssetAfter=function(a,b){throw Error("InjectAuiAssets is an unsupported tag in Javascript targets");},b.prototype.isAmazonImageCompatible=function(a){return xa.isOperationsAllowed(a.trim())},b.prototype.getSrcset=function(a,b,c,k,d){return xa.generateSrcset(a.trim(),b,c,k,d)},b.prototype.getCacheBuster=
function(a,b,c,k){return xa.generateCacheBuster(a.trim(),b,c,k)},b}(),eb=(Y=function(b,a){return Y=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Y(b,a)},function(b,a){function c(){this.constructor=b}Y(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}),fa=function(){return fa=Object.assign||function(b){for(var a,c=1,r=arguments.length;c<r;c++)for(var k in a=arguments[c])Object.prototype.hasOwnProperty.call(a,
k)&&(b[k]=a[k]);return b},fa.apply(this,arguments)},Z=function(b){function a(a){return b.call(this,a)||this}return eb(a,b),a.prototype.isTableEmpty=function(a){return 0===Object.keys(a).length},a.prototype.tableMerge=function(a,b){return fa(fa({},a),b)},a.prototype.range=function(a,b){b=Math.abs(b-a)+1;var c=this.decToInt(a);return Array.from({length:this.decToInt(b)},function(a,b){return c+b})},a}(ya),I={Button:function(b,a,d){var r,k,f,g,m,h,n,t,u,da,e=new Z(b.context||{}),A=void 0!==a.aria&&null!==
a.aria?a.aria:{},ea=void 0!==a.buttonModifier&&null!==a.buttonModifier?a.buttonModifier:"Unspecified",D=void 0!==a.buttonPosition&&null!==a.buttonPosition?a.buttonPosition:"Unspecified",va=void 0!==a.buttonSize&&null!==a.buttonSize?a.buttonSize:"Base",l=void 0!==a.buttonType&&null!==a.buttonType?a.buttonType:"Unspecified",F=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",cb=void 0!==a.data&&null!==a.data?a.data:{},B=void 0!==a.formAction&&null!==a.formAction?a.formAction:"",Ha=void 0!==a.gridUnits&&
null!==a.gridUnits?a.gridUnits:0,G=void 0!==a.hideIcon&&null!==a.hideIcon&&a.hideIcon,wa=void 0!==a.htmlButtonType&&null!==a.htmlButtonType?a.htmlButtonType:"Submit",X=void 0!==a.htmlTitle&&null!==a.htmlTitle?a.htmlTitle:"",E=void 0!==a.id&&null!==a.id?a.id:"",za=void 0!==a.isInButtonGroup&&null!==a.isInButtonGroup&&a.isInButtonGroup,P=void 0!==a.name&&null!==a.name?a.name:"",R=void 0!==a.nativeCssClass&&null!==a.nativeCssClass?a.nativeCssClass:"",S=void 0!==a.nativeId&&null!==a.nativeId?a.nativeId:
"",I=void 0!==a.position&&null!==a.position?a.position:"Unspecified",Q=void 0!==a.rel&&null!==a.rel?a.rel:"",Ja=void 0!==a.spacing&&null!==a.spacing?a.spacing:"Unspecified",U=void 0!==a.spacingTop&&null!==a.spacingTop?a.spacingTop:"Unspecified",T=void 0!==a.status&&null!==a.status?a.status:"Unspecified",aa=void 0!==a.tabindex&&null!==a.tabindex?a.tabindex:0,O=void 0!==a.target&&null!==a.target?a.target:"",ba=void 0!==a.textAlign&&null!==a.textAlign?a.textAlign:"Unspecified",H=void 0!==a.tooltip&&
null!==a.tooltip?a.tooltip:"",M=void 0!==a.tooltipPosition&&null!==a.tooltipPosition?a.tooltipPosition:"TriggerTop",N=void 0!==a.unsafeUrl&&null!==a.unsafeUrl?a.unsafeUrl:"",ia=void 0!==a.url&&null!==a.url?a.url:"",K=void 0!==a.value&&null!==a.value?a.value:"",Y=void 0!==a.widthNamed&&null!==a.widthNamed?a.widthNamed:"Unspecified";return b.root("aui","Button",[[[(r=e.normalizeTable(e.encodeAttrs(e.tableMerge(V(a,"data"),cb))),[(k=e.normalizeTable(e.tableMerge(V(a,"aria"),A)),[b.createElement("span",
(da={},y(da,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),""!==E&&(da.id=E),da.class=J(["a-button","Unspecified"!==T?"a-button-"+c(T):"","Unspecified"!==ea?"a-button-"+q(ea):"","Unspecified"!==I?"a-button-group"+w(I):"","Unspecified"!==Ja?"a-spacing-"+L(Ja):"","Unspecified"!==U?"a-spacing-top-"+v(U):"",0!==Ha?"a-button-span"+
Ha:"","Unspecified"!==D?"a-"+C(D):"","Sns"===l||"Cart"===l?" a-button-primary":"BuyNow"===l?" a-button-oneclick":"OneClickPreorder"===l||"BuyNowPreorder"===l?" a-button-preorder a-button-preorder-secondary":"ToggleUnavailable"===l?" a-button-toggle a-button-unavailable":"Unspecified"===l?"a-button-base":"a-button-"+ca(l),("Small"===va?" a-button-small":"")+("Base"===Y?" a-button-width-normal":""),"Sns"===l||"Cart"===l||"OneClick"===l||"BuyNow"===l||"Preorder"===l||"OneClickPreorder"===l||"BuyNowPreorder"===
l?" a-button-icon":"",""!==F?""+F:""]),da),b.createElement("span",(u={},y(u,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),u.class="a-button-inner",u),G||"Small"===va||"Sns"!==l&&"Cart"!==l&&"OneClick"!==l&&"BuyNow"!==l&&"Preorder"!==l&&"OneClickPreorder"!==l&&"BuyNowPreorder"!==l?void 0:b.createElement("i",(t={},y(t,
"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),t.class=J(["a-icon","OneClick"===l?"a-icon-1click":"Preorder"===l?"a-icon-cart":"OneClickPreorder"===l?"a-icon-1click":"BuyNowPreorder"===l?"a-icon-buynow":"a-icon-"+ca(l)]),t)),"Small"!==va&&"Supplemental"===ea||"Dropdown"===ea?b.createElement("i",(n={},y(n,"",e.normalizeTable("T1"===
e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),n.class=J(["a-icon","a-icon-"+q(ea)]),n)):void 0,""!==ia||""!==N?b.createElement("a",(h={},y(h,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
e.emptyTable())),""!==S&&(h.id=S),0!==aa&&(h.tabindex=""+aa),""!==ia?h.href=e.unescapeHtml(ia):""!==N&&(h.href=e.unescapeHtml(N)),"Disabled"===T&&(h["aria-disabled"]="true"),""!==P&&(h.name=P),""===X&&""===H||(h.title=""!==H?H:X),""!==O&&(h.target=O),y(h,"",""!==e.trim(e.join(" ",[Q,""===O||e.variant("marketplace:cn")||e.variant("marketplace:in")||e.variant("marketplace:jp")?"":"noopener"]))?e.tableOf("rel",e.trim(e.join(" ",[Q,""===O||e.variant("marketplace:cn")||e.variant("marketplace:in")||e.variant("marketplace:jp")?
"":"noopener"]))):e.emptyTable()),za&&(h.role="radio",h["aria-checked"]="Selected"===T?"true":"false"),y(h,"data-",r),y(h,"aria-",k),h.class=J(["a-button-text","Unspecified"!==ba?"a-text-"+p(ba):"",""!==H?"a-declarative":"",""!==R?""+R:""]),""!==H&&y(h,"",e.normalizeTable(e.tableMerge("C"===e.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?e.tableMerge(e.tableMerge(e.tableOf("data-csa-c-type","widget"),e.tableOf("data-csa-c-func-deps","aui-da-a-tooltip")),e.tableOf("data-csa-interaction-events",
"click")):e.emptyTable(),e.tableMerge(e.tableMerge(e.tableOf("data-action","a-tooltip"),e.tableOf("data-a-tooltip",'{"position":"'+z(M)+'","content":"'+H+'","allowLinkDefault": true}')),e.tnr("click mouseenter mouseleave focus focusin blur focusout".split(" ")))))),h),d):"Submit"===wa?[b.createElement("input",(m={},y(m,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
e.emptyTable())),""!==S&&(m.id=S),0!==aa&&(m.tabindex=""+aa),""!==P&&(m.name=P),""===X&&""===H||(m.title=""!==H?H:X),""!==O&&(m.target=O),y(m,"",""!==e.trim(e.join(" ",[Q,""===O||e.variant("marketplace:cn")||e.variant("marketplace:in")||e.variant("marketplace:jp")?"":"noopener"]))?e.tableOf("rel",e.trim(e.join(" ",[Q,""===O||e.variant("marketplace:cn")||e.variant("marketplace:in")||e.variant("marketplace:jp")?"":"noopener"]))):e.emptyTable()),za&&(m.role="radio",m["aria-checked"]="Selected"===T?"true":
"false"),y(m,"data-",r),y(m,"aria-",k),"Disabled"===T&&(m.disabled="disabled"),m.class=J(["a-button-input",""!==H?"a-declarative":"",""!==R?""+R:""]),m.type=x(wa),null!==a.formId&&void 0!==a.formId&&(m.form=a.formId),""!==B&&(m.formaction=e.unescapeHtml(B)),""!==K&&(m.value=K),""!==H&&y(m,"",e.normalizeTable(e.tableMerge("C"===e.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?e.tableMerge(e.tableMerge(e.tableOf("data-csa-c-type","widget"),e.tableOf("data-csa-c-func-deps","aui-da-a-tooltip")),
e.tableOf("data-csa-interaction-events","click")):e.emptyTable(),e.tableMerge(e.tableMerge(e.tableOf("data-action","a-tooltip"),e.tableOf("data-a-tooltip",'{"position":"'+z(M)+'","content":"'+H+'","allowLinkDefault": true}')),e.tnr("click mouseenter mouseleave focus focusin blur focusout".split(" ")))))),""===E||null!==k.label&&void 0!==k.label||(m["aria-labelledby"]=E+"-announce"),m)),b.createElement("span",(g={},y(g,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),""!==E&&(g.id=E+"-announce"),g.class=J(["a-button-text","Unspecified"!==ba?"a-text-"+p(ba):""]),g["aria-hidden"]="true",g),d)]:b.createElement("button",(f={},y(f,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
e.emptyTable())),""!==S&&(f.id=S),""!==E&&""===S&&(f.id=E+"-announce"),0!==aa&&(f.tabindex=""+aa),""!==P&&(f.name=P),""===X&&""===H||(f.title=""!==H?H:X),""!==O&&(f.target=O),y(f,"",""!==e.trim(e.join(" ",[Q,""===O||e.variant("marketplace:cn")||e.variant("marketplace:in")||e.variant("marketplace:jp")?"":"noopener"]))?e.tableOf("rel",e.trim(e.join(" ",[Q,""===O||e.variant("marketplace:cn")||e.variant("marketplace:in")||e.variant("marketplace:jp")?"":"noopener"]))):e.emptyTable()),za&&(f.role="radio",
f["aria-checked"]="Selected"===T?"true":"false"),y(f,"data-",r),y(f,"aria-",k),"Disabled"===T&&(f.disabled="disabled"),f.class=J(["a-button-text","Unspecified"!==ba?"a-text-"+p(ba):"",""!==H?"a-declarative":"",""!==R?""+R:""]),f.type=x(wa),null!==a.formId&&void 0!==a.formId&&(f.form=a.formId),""!==B&&(f.formaction=e.unescapeHtml(B)),""!==K&&(f.value=K),""!==H&&y(f,"",e.normalizeTable(e.tableMerge("C"===e.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?e.tableMerge(e.tableMerge(e.tableOf("data-csa-c-type",
"widget"),e.tableOf("data-csa-c-func-deps","aui-da-a-tooltip")),e.tableOf("data-csa-interaction-events","click")):e.emptyTable(),e.tableMerge(e.tableMerge(e.tableOf("data-action","a-tooltip"),e.tableOf("data-a-tooltip",'{"position":"'+z(M)+'","content":"'+H+'","allowLinkDefault": true}')),e.tnr("click mouseenter mouseleave focus focusin blur focusout".split(" ")))))),f),d)))])])]]])},Text:function(b,a,c){var d,k,f,m=new Z(b.context||{}),h=void 0!==a.aria&&null!==a.aria?a.aria:{},g=void 0!==a.cssClass&&
null!==a.cssClass?a.cssClass:"",n=void 0!==a.data&&null!==a.data?a.data:{},q=void 0!==a.id&&null!==a.id?a.id:"",p=void 0!==a.role&&null!==a.role?a.role:"Unspecified",w=void 0!==a.textBold&&null!==a.textBold&&a.textBold,e=void 0!==a.textCapitalize&&null!==a.textCapitalize&&a.textCapitalize,t=void 0!==a.textColor&&null!==a.textColor?a.textColor:"Unspecified",u=void 0!==a.textDirection&&null!==a.textDirection?a.textDirection:"Unspecified",z=void 0!==a.textEmphasis&&null!==a.textEmphasis&&a.textEmphasis,
x=void 0!==a.textNormal&&null!==a.textNormal&&a.textNormal,l=void 0!==a.textNowrap&&null!==a.textNowrap&&a.textNowrap,v=void 0!==a.textPosition&&null!==a.textPosition?a.textPosition:"Unspecified",L=void 0!==a.textQuote&&null!==a.textQuote&&a.textQuote,B=void 0!==a.textSize&&null!==a.textSize?a.textSize:"Unspecified",y=void 0!==a.textStrikethrough&&null!==a.textStrikethrough&&a.textStrikethrough;return b.root("aui","Text",[[[b.createElement("span",(f={},oa(f,"",m.normalizeTable("T1"===m.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
m.tableMerge(m.tableOf("data-a-version","3.25.5"),m.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):m.emptyTable())),""!==q&&(f.id=q),oa(f,"data-",m.normalizeTable(m.encodeAttrs(m.tableMerge(Da(a,"data"),n)))),oa(f,"aria-",m.normalizeTable(m.tableMerge(Da(a,"aria"),h))),f.class=(d=["Unspecified"!==B?"a-size-"+Ra(B):"","Unspecified"!==t?"a-color-"+Sa(t):"","Unspecified"!==v?"a-"+Ta(v):"",g,m.trim(m.join("",[w?"a-text-bold":"",e?" a-text-caps":"",z?" a-text-italic":"",l?
" a-nowrap":"",L?" a-text-quote":"",y?" a-text-strike":"",x?" a-text-normal":""]))],0<(k=d.join(" ").split(" ").filter(Ua).join(" ")).length?k:void 0),"Unspecified"!==p&&(f.role=function(a){switch(a){case "Unspecified":return"unspecified";case "Alert":return"alert";case "AlertDialog":return"alertdialog";case "Application":return"application";case "Article":return"article";case "Banner":return"banner";case "Button":return"button";case "Checkbox":return"checkbox";case "ColumnHeader":return"columnheader";
case "ComboBox":return"combobox";case "Complementary":return"complementary";case "ContentInfo":return"contentinfo";case "Definition":return"definition";case "Dialog":return"dialog";case "Directory":return"directory";case "Document":return"document";case "Form":return"form";case "Grid":return"grid";case "GridCell":return"gridcell";case "Group":return"group";case "Heading":return"heading";case "Img":return"img";case "Link":return"link";case "List":return"list";case "ListBox":return"listbox";case "ListItem":return"listitem";
case "Log":return"log";case "Main":return"main";case "Marquee":return"marquee";case "Math":return"math";case "Menu":return"menu";case "MenuBar":return"menubar";case "MenuItem":return"menuitem";case "MenuItemCheckbox":return"menuitemcheckbox";case "MenuItemRadio":return"menuitemradio";case "Navigation":return"navigation";case "Note":return"note";case "Option":return"option";case "Presentation":return"presentation";case "ProgressBar":return"progressbar";case "Radio":return"radio";case "RadioGroup":return"radiogroup";
case "Region":return"region";case "Row":return"row";case "RowGroup":return"rowgroup";case "RowHeader":return"rowheader";case "Scrollbar":return"scrollbar";case "Search":return"search";case "Separator":return"separator";case "Slider":return"slider";case "SpinButton":return"spinbutton";case "Status":return"status";case "Tab":return"tab";case "TabList":return"tablist";case "TabPanel":return"tabpanel";case "TextBox":return"textbox";case "Timer":return"timer";case "Toolbar":return"toolbar";case "Tooltip":return"tooltip";
case "Tree":return"tree";case "TreeGrid":return"treegrid";case "TreeItem":return"treeitem";default:return a}}(p)),"Unspecified"!==u&&(f.dir=function(a){switch(a){case "Unspecified":return"unspecified";case "Ltr":return"ltr";case "Rtl":return"rtl";case "Auto":return"auto";default:return a}}(u)),f),c)]]])},DeclarativeAction:function(b,a,c){var d,k=new Z(b.context||{}),f=void 0!==a.actionName&&null!==a.actionName?a.actionName:"",m=void 0!==a.actionParams&&null!==a.actionParams?a.actionParams:{},h=void 0!==
a.extra&&null!==a.extra?a.extra:"";a=void 0!==a.id&&null!==a.id?a.id:"";return b.root("aui","DeclarativeAction",[[[b.createElement("span",(d={},pa(d,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),d.class="a-declarative",d["data-action"]=f,"C"===k.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")&&(d["data-csa-c-type"]=
"widget",d["data-csa-c-func-deps"]="aui-da-"+f),pa(d,"data-",k.tableOf(f,JSON.stringify(m).replace(/</g,"\\u003c"))),""!==a&&(d.id=a),""!==h&&pa(d,"",k.parseAttrs(h)),d),c)]]])},Price:function(b,a,c){var d,k,f,m,h,g,n,q,p,w,e,t,z,x,v,l=new Z(b.context||{});c=void 0!==a.altText&&null!==a.altText?a.altText:"";var L=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",y=void 0!==a.currencySymbol&&null!==a.currencySymbol?a.currencySymbol:"",B=void 0!==a.currencySymbolPosition&&null!==a.currencySymbolPosition?
a.currencySymbolPosition:"Left",A=void 0!==a.decimalSeparator&&null!==a.decimalSeparator?a.decimalSeparator:"",G=void 0!==a.fractionalValue&&null!==a.fractionalValue?a.fractionalValue:"",F=void 0!==a.id&&null!==a.id?a.id:"",C=void 0!==a.priceColor&&null!==a.priceColor?a.priceColor:"Unspecified",E=void 0!==a.priceSize&&null!==a.priceSize?a.priceSize:"Large",I=void 0!==a.strikethrough&&null!==a.strikethrough&&a.strikethrough;a=void 0!==a.wholeValue&&null!==a.wholeValue?a.wholeValue:"";return b.root("aui",
"Price",[[[(d=l.variant("rtl:true"),[["Mini"===E||"Small"===E||"Base"===E?b.createElement("span",(v={},D(v,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),""!==F&&(v.id=F),v.class=N(["a-price","a-text-price",L]),"Base"===E&&(v["data-a-size"]="b"),"Small"===E&&(v["data-a-size"]="s"),"Mini"===E&&(v["data-a-size"]="mini"),
I&&(v["data-a-strike"]="true"),"Unspecified"!==C&&(v["data-a-color"]=Ea(C)),v),b.createElement("span",(x={},D(x,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),x.class="a-offscreen",x),""!==c?u(0,{content:c}):d?["Left"===B?b.createElement("span",(z={},D(z,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),z.dir="rtl",z),u(0,{content:y})):void 0,"‎",u(0,{content:a}),""!==G?[u(0,{content:A}),u(0,{content:G})]:void 0,"Right"===B?b.createElement("span",(t={},D(t,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
l.emptyTable())),t.dir="rtl",t),u(0,{content:y})):void 0,"‎"]:["Left"===B?u(0,{content:y}):void 0,u(0,{content:a}),""!==G?[u(0,{content:A}),u(0,{content:G})]:void 0,"Right"===B?u(0,{content:y}):void 0]),b.createElement("span",(e={},D(e,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),e["aria-hidden"]="true",d&&(e.dir=
"ltr"),e),d?["Left"===B?b.createElement("span",(w={},D(w,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),w.dir="rtl",w),u(0,{content:y})):void 0,"‎",u(0,{content:a}),""!==G?[u(0,{content:A}),u(0,{content:G})]:void 0,"Right"===B?b.createElement("span",(p={},D(p,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),p.dir="rtl",p),u(0,{content:y})):void 0,"‎"]:["Left"===B?u(0,{content:y}):void 0,u(0,{content:a}),""!==G?[u(0,{content:A}),u(0,{content:G})]:void 0,"Right"===B?u(0,{content:y}):void 0])):b.createElement("span",(q={},D(q,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),
l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),""!==F&&(q.id=F),q.class=N(["a-price",L]),"ExtraExtraLarge"===E&&(q["data-a-size"]="xxl"),"ExtraLarge"===E&&(q["data-a-size"]="xl"),"Large"===E&&(q["data-a-size"]="l"),"Medium"===E&&(q["data-a-size"]="m"),"BasePlus"===E&&(q["data-a-size"]="base_plus"),"MediumPlus"===E&&(q["data-a-size"]="medium_plus"),q["data-a-color"]=""+("Unspecified"===C?"base":Ea(C)),q),b.createElement("span",(n={},D(n,"",l.normalizeTable("T1"===
l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),n.class="a-offscreen",n),""!==c?u(0,{content:c}):d?["Left"===B?b.createElement("span",(g={},D(g,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
l.emptyTable())),g.dir="rtl",g),u(0,{content:y})):void 0,"‎",u(0,{content:a}),""!==G?[u(0,{content:A}),u(0,{content:G})]:void 0,"Right"===B?b.createElement("span",(h={},D(h,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),h.dir="rtl",h),u(0,{content:y})):void 0,"‎"]:["Left"===B?u(0,{content:y}):void 0,u(0,{content:a}),
""!==G?[u(0,{content:A}),u(0,{content:G})]:void 0,"Right"===B?u(0,{content:y}):void 0]),b.createElement("span",(m={},D(m,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),m["aria-hidden"]="true",d&&(m.dir="ltr"),m),"Left"===B?[[[b.createElement("span",function(){var a={};return D(a,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),a.class=N(["a-price-symbol"]),d&&(a.dir="rtl"),a}(),u(0,{content:y})),d?"‎":void 0]]]:void 0,b.createElement("span",(f={},D(f,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),
f.class="a-price-whole",f),u(0,{content:a}),""!==G?[[[b.createElement("span",function(){var a={};return D(a,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),a.class=N(["a-price-decimal"]),d&&(a.dir="ltr"),a}(),u(0,{content:A})),d?"‎":void 0]]]:void 0),""!==G?b.createElement("span",(k={},D(k,"",l.normalizeTable("T1"===
l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):l.emptyTable())),k.class="a-price-fraction",k),u(0,{content:G})):void 0,"Right"===B?[[[b.createElement("span",function(){var a={};return D(a,"",l.normalizeTable("T1"===l.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?l.tableMerge(l.tableOf("data-a-version","3.25.5"),l.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
l.emptyTable())),a.class=N(["a-price-symbol"]),d&&(a.dir="rtl"),a}(),u(0,{content:y})),d?"‎":void 0]]]:void 0)),d?"‏":void 0]])]]])},Dropdown:function(b,a,c){var d,k,f,m,h,g,q,n,p,w,e=new Z(b.context||{}),t=void 0!==a.actionId&&null!==a.actionId?a.actionId:"",z=void 0!==a.aria&&null!==a.aria?a.aria:{},y=void 0!==a.ariaLabel&&null!==a.ariaLabel?a.ariaLabel:"",x=void 0!==a.buttonSize&&null!==a.buttonSize?a.buttonSize:"Base",l=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",A=void 0!==a.data&&null!==
a.data?a.data:{},C=void 0!==a.dropdownMaxHeight&&null!==a.dropdownMaxHeight?a.dropdownMaxHeight:"",B=void 0!==a.gridUnits&&null!==a.gridUnits?a.gridUnits:0,D=void 0!==a.hasFooter&&null!==a.hasFooter&&a.hasFooter,G=void 0!==a.hasImages&&null!==a.hasImages&&a.hasImages,I=void 0!==a.id&&null!==a.id?a.id:"",J=void 0!==a.labelText&&null!==a.labelText?a.labelText:"",E=void 0!==a.name&&null!==a.name?a.name:"",M=void 0!==a.nativeCssClass&&null!==a.nativeCssClass?a.nativeCssClass:"",P=void 0!==a.nativeId&&
null!==a.nativeId?a.nativeId:"",R=void 0!==a.optionPrompt&&null!==a.optionPrompt?a.optionPrompt:"",S=void 0!==a.selectedOption&&null!==a.selectedOption?a.selectedOption:"",N=void 0!==a.spacing&&null!==a.spacing?a.spacing:"Unspecified",Q=void 0!==a.spacingTop&&null!==a.spacingTop?a.spacingTop:"Unspecified",K=void 0!==a.status&&null!==a.status?a.status:"Unspecified",U=void 0!==a.touchHeader&&null!==a.touchHeader?a.touchHeader:"",T=void 0!==a.widthNamed&&null!==a.widthNamed?a.widthNamed:"Unspecified";
return b.root("aui","Dropdown",[[[b.createElement("span",(w={},F(w,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),w.class="a-dropdown-container",w),""!==J?b.createElement("label",(p={},F(p,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),
e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),""!==P&&(p.for=P),p.class=ja(["a-native-dropdown",M]),p),u(0,{content:J})):void 0,b.createElement("select",(n={},F(n,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),n.name=E,n.autocomplete="off",n.role="combobox",G&&(n["data-a-has-images"]=
G?"true":"false"),""!==M&&(n["data-a-native-class"]=M),""!==U&&(n["data-a-touch-header"]=U),""!==C&&(n["data-a-max-height"]=C),""!==t&&(n["data-a-action-id"]=t),D&&(n["data-a-has-footer"]=D?"true":"false"),""!==P&&(n.id=P),n.tabindex="0",n["data-action"]="a-dropdown-select",F(n,"aria-",e.normalizeTable(e.tableMerge(ka(a,"aria"),z))),""!==y&&(n["aria-label"]=y),n.class=ja(["a-native-dropdown",0!==B?"a-button-span"+B:"","Unspecified"!==N?"a-spacing-"+L(N):"","Unspecified"!==Q?"a-spacing-top-"+v(Q):
"","a-declarative",M]),"Disabled"===K&&(n.disabled="disabled"),n),""!==R?b.createElement("option",(q={},F(q,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),q.class="a-prompt",q.value="",q),u(0,{content:R})):void 0,c),b.createElement("span",(g={},F(g,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),g.tabindex="-1",""!==I&&(g.id=I),F(g,"data-",e.normalizeTable(e.encodeAttrs(e.tableMerge(ka(a,"data"),A)))),""!==l&&(g["data-a-class"]=l),g.class=ja(["a-button","a-button-dropdown",("Small"===x?" a-button-small":"")+("Base"===T?" a-button-width-normal":""),"Unspecified"!==N?"a-spacing-"+L(N):"","Unspecified"!==Q?"a-spacing-top-"+v(Q):"",0!==B?"a-button-span"+
B:"",l,"Disabled"===K?"a-button-disabled":"Error"===K?"a-button-error":""]),g["aria-hidden"]="true","Disabled"===K&&(g["aria-disabled"]="true"),g),b.createElement("span",(h={},F(h,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),h.class="a-button-inner",h),b.createElement("span",(m={},F(m,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),m.class="a-button-text a-declarative",F(m,"data-",e.normalizeTable(e.encodeAttrs(e.tableMerge(ka(a,"data"),e.tableMerge(e.emptyTable(),"C"===e.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?e.tableMerge(e.tableMerge(e.tableOf("csa-c-type","widget"),e.tableOf("csa-c-func-deps","aui-da-a-dropdown-button")),e.tableOf("csa-interaction-events",
"click")):e.emptyTable()))))),m["data-action"]="a-dropdown-button",m["aria-hidden"]="true","Disabled"!==K&&F(m,"",e.tnr(["click","keydown"])),m),""!==J?b.createElement("span",(f={},F(f,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),f.class="a-dropdown-label",f),u(0,{content:J})):void 0,b.createElement("span",(k={},F(k,
"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):e.emptyTable())),k.class="a-dropdown-prompt",k),u(0,{content:""!==S?S:R}))),b.createElement("i",(d={},F(d,"",e.normalizeTable("T1"===e.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?e.tableMerge(e.tableOf("data-a-version","3.25.5"),e.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
e.emptyTable())),d.class="a-icon a-icon-dropdown",d)))))]]])},DropdownOption:function(b,a,c){var d,k,f=new Z(b.context||{}),m=void 0!==a.aria&&null!==a.aria?a.aria:{},h=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",g=void 0!==a.data&&null!==a.data?a.data:{},n=void 0!==a.htmlContent&&null!==a.htmlContent?a.htmlContent:"",q=void 0!==a.id&&null!==a.id?a.id:"",p=void 0!==a.imageSource&&null!==a.imageSource?a.imageSource:"",w=void 0!==a.labelText&&null!==a.labelText?a.labelText:"",e=void 0!==a.nativeCssClass&&
null!==a.nativeCssClass?a.nativeCssClass:"",t=void 0!==a.nativeId&&null!==a.nativeId?a.nativeId:"",u=void 0!==a.optionFaded&&null!==a.optionFaded&&a.optionFaded,z=void 0!==a.selected&&null!==a.selected&&a.selected,v=void 0!==a.value&&null!==a.value?a.value:"";return b.root("aui","DropdownOption",[[[b.createElement("option",(k={},na(k,"",f.normalizeTable("T1"===f.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?f.tableMerge(f.tableOf("data-a-version","3.25.5"),f.tableOf("data-a-templates-pcv",
"2aa3df790132a40705a7b35daf432dc0650cbd39")):f.emptyTable())),na(k,"data-",f.normalizeTable(f.encodeAttrs(f.tableMerge(Ca(a,"data"),g)))),na(k,"aria-",f.normalizeTable(f.tableMerge(Ca(a,"aria"),m))),k.value=v,""!==e&&(k.class=0<(d=[e].join(" ").split(" ").filter(Qa).join(" ")).length?d:void 0),(u||""!==h)&&(k["data-a-css-class"]=f.trim(f.join(" ",[h,u?"a-color-tertiary":""]))),""!==t&&(k.id=t),""!==q&&(k["data-a-id"]=q),""!==n&&(k["data-a-html-content"]=n),""!==p&&(k["data-a-image-source"]=p),""!==
w&&(k.label=w),z&&(k.selected=!0),k),c)]]])}},Ya=function(b,a,c){c=void 0!==a.selectQuantityText&&null!==a.selectQuantityText?a.selectQuantityText:"";var d=void 0!==a.asinImageUrl&&null!==a.asinImageUrl?a.asinImageUrl:"",k=void 0!==a.pricePerUnitDisplayString&&null!==a.pricePerUnitDisplayString?a.pricePerUnitDisplayString:"",f=void 0!==a.estTotalPriceText&&null!==a.estTotalPriceText?a.estTotalPriceText:"",m=void 0!==a.estTotalWeightText&&null!==a.estTotalWeightText?a.estTotalWeightText:"",h=void 0!==
a.itemWeightUnit&&null!==a.itemWeightUnit?a.itemWeightUnit:"",g=void 0!==a.currencySymbolPosition&&null!==a.currencySymbolPosition?a.currencySymbolPosition:"Left",n=void 0!==a.summaryDisclaimerText&&null!==a.summaryDisclaimerText?a.summaryDisclaimerText:"",q=void 0!==a.summaryAtcButtonText&&null!==a.summaryAtcButtonText?a.summaryAtcButtonText:"",p=void 0!==a.quantitySelectorUnitText&&null!==a.quantitySelectorUnitText?a.quantitySelectorUnitText:"";b.assertNotNull(a,"selectQuantityText asinImageUrl estTotalPriceText itemWeightUnit currencySymbolPosition summaryDisclaimerText summaryAtcButtonText selectorDisplayValues priceSymbol priceDecimalSeparator".split(" "));
var w,e=b.dynamicInstance("aui","Text",I),t=b.dynamicInstance("aui","Price",I),u=b.dynamicInstance("aui","Button",I),z=b.dynamicInstance("aui","DeclarativeAction",I);return b.root("@amzn/portablecta","VariableWeightMobile",[b.createElement("div",{class:"pvw-bs-container"},e(b,{textBold:!0,cssClass:"pvw-bs-heading",id:"pvw-bs-heading-id"},[c]),b.createElement("div",{class:"pvw-bs-content-container"},b.createElement("div",{class:"pvw-asin-image-container"},b.createElement("img",{class:"pvw-asin-image",
src:d})),b.createElement("div",{class:"pvw-scroll-picker-wrapper"},b.createElement("div",{class:"pvw-scroll-picker"},b.createElement("div",{class:"pvw-scroll-picker-mask"}),b.createElement("ul",{class:"pvw-scroll-picker-list",role:"listbox",tabindex:"0","aria-labelledby":"pvw-bs-heading-id"},(w=a.selectorDisplayValues,!w.map&&Java.from?Java.from(w):w).map(function(a){return[b.createElement("li",{class:"pvw-scroll-picker-item",role:"option",tabindex:"-1"},b.createElement("span",{},a))]}),b.createElement("li",
{class:"pvw-scroll-picker-item","aria-hidden":"true"}))),b.createElement("div",{class:"pvw-scroll-picker-overlay"})),b.createElement("div",{class:"pvw-selector-unit-text"},p)),b.createElement("div",{class:"pvw-bs-summary"},b.createElement("div",{class:"pvw-bs-est-wrapper"},b.createElement("div",{},e(b,{textSize:"Small",textBold:!0,cssClass:"aok-block"},[k]),null!==a.estSingleItemWeight&&void 0!==a.estSingleItemWeight?b.createElement("div",{class:"pvw-bs-item-weight-wrapper"},e(b,{textSize:"Small"},
[m]),e(b,{textSize:"Small",cssClass:"pvw-bs-item-weight"},[""+a.estSingleItemWeight]),e(b,{textSize:"Small"},[h])):void 0),b.createElement("div",{class:"pvw-bs-price-wrapper"},e(b,{textColor:"Base",textSize:"Small",cssClass:"aok-block"},[f]),t(b,{currencySymbol:a.priceSymbol,currencySymbolPosition:g,decimalSeparator:a.priceDecimalSeparator,fractionalValue:"00",priceSize:"ExtraExtraLarge"},[]))),e(b,{textSize:"Mini",cssClass:"pvw-bs-summary-disclaimer aok-block"},[n]),z(b,{actionName:"pvw-bs-atc-click"},
[u(b,{buttonType:"Primary",buttonSize:"Base",widthNamed:"Large",htmlButtonType:"Button"},[q])])))])},Xa=function(b,a,c){c=void 0!==a.summaryAtcButtonText&&null!==a.summaryAtcButtonText?a.summaryAtcButtonText:"";var d=void 0!==a.disclaimerText&&null!==a.disclaimerText?a.disclaimerText:"",k=void 0!==a.aboutEstimationText&&null!==a.aboutEstimationText?a.aboutEstimationText:"";b.assertNotNull(a,["summaryAtcButtonText","selectorDisplayValues","disclaimerText","aboutEstimationText"]);var f,m=b.dynamicInstance("aui",
"Text",I),h=b.dynamicInstance("aui","Button",I),g=b.dynamicInstance("aui","DeclarativeAction",I);return b.root("@amzn/portablecta","VariableWeightMobileV2",[b.createElement("div",{class:"pvw-bs-container-v2"},b.createElement("div",{class:"pvw-bs-content-container-v2"},b.createElement("div",{class:"pvw-scroll-picker-wrapper"},b.createElement("div",{class:"pvw-scroll-picker-v2"},b.createElement("ul",{class:"pvw-scroll-picker-list-v2",role:"listbox",tabindex:"0"},(f=a.selectorDisplayValues,!f.map&&Java.from?
Java.from(f):f).map(function(a){return[b.createElement("li",{class:"pvw-scroll-picker-item-v2",role:"option",tabindex:"-1"},b.createElement("span",{},a))]}),b.createElement("li",{class:"pvw-scroll-picker-item-v2"}),b.createElement("li",{class:"pvw-scroll-picker-item-v2"}))),b.createElement("div",{class:"pvw-scroll-picker-overlay-v2"}))),b.createElement("div",{class:"pvw-bs-disclaimer-wrapper"},b.createElement("div",{class:"pvw-bs-disclaimer-container"},m(b,{cssClass:"pvw-about-est-text",textBold:!0},
[k]),m(b,{},[d]))),b.createElement("div",{class:"pvw-atc-button-container"},g(b,{actionName:"pvw-bs-atc-click"},[h(b,{buttonType:"Primary",buttonSize:"Base",widthNamed:"Large",htmlButtonType:"Button"},[c])])))])},$a=function(b,a,c){b.assertNotNull(a,["asin","selectedOption","dropdownOptions"]);var d,f=b.dynamicInstance("aui","DropdownOption",I);c=b.dynamicInstance("aui","Dropdown",I);return b.root("@amzn/portablecta","VariableWeightDesktop",[b.createElement("div",{class:"pvw-dropdown-container"},
c(b,{cssClass:"pvw-dropdown",name:a.asin,actionId:"pvw-dropdown-"+a.asin,hasFooter:!0,dropdownMaxHeight:"237px",selectedOption:a.selectedOption},[(d=a.dropdownOptions,!d.map&&Java.from?Java.from(d):d).map(function(c){return[f(b,{cssClass:"pvw-dropdown-option",value:c.value,htmlContent:c.displayValue,selected:c.value===a.selectedOption},[c.displayText])]})]))])},fb=0;ya=function(){function b(){Aa(this,b);this.context={}}Ba(b,[{key:"generateInstanceId",value:function(){return"inst"+fb++}},{key:"root",
value:function(a,b,c){var d=new Set;return qa(c).filter(function(a){return!!a}).map(function(a){a=Fa(a);return d.has(a)?a.cloneNode(!0):(d.add(a),a)})}},{key:"createElement",value:function(a,b){for(var c=document.createElement(a),d=arguments.length,f=Array(2<d?d-2:0),h=2;h<d;h++)f[h-2]=arguments[h];return Object.entries(b).forEach(function(a){a=M(a,2);return c.setAttribute(a[0],a[1])}),qa(f).forEach(function(a){return c.appendChild(Fa(a))}),c}},{key:"assertNotNull",value:function(a,b){var c=!0,d=
!1,f=A;try{for(var h=b[Symbol.iterator](),g;!(c=(g=h.next()).done);c=!0){var m=g.value;if(!a.hasOwnProperty(m)||null==m)throw Error("Required template key is undefined: "+m);}}catch(bb){d=!0,f=bb}finally{try{!c&&h.return&&h.return()}finally{if(d)throw f;}}}},{key:"createComment",value:function(a){return document.createComment(a)}},{key:"createDoctype",value:function(a){return document.implementation.createDocumentType(a,"","")}},{key:"shallowMerge",value:function(a,b){return Object.assign(Object.assign({},
a),b)}},{key:"dynamicInstance",value:function(a,b,c){}},{key:"testCondition",value:function(a){return!1}}]);return b}();var ra;!function(b){b.V1="V1";b.V2="V2"}(ra||(ra={}));var sa=new (function(b){function a(){Aa(this,a);var b=Ka(this,(a.__proto__||Object.getPrototypeOf(a)).apply(this,arguments));b;b.context={variants:[],attributes:{},weblabProvider:{getTreatmentRecordTrigger:function(){return"C"},getTreatmentNoTrigger:function(){return"C"},isActive:!1}};return b}La(a,b);Ba(a,[{key:"createElement",
value:function(a,b){for(var c=document.createElement(a),d=arguments.length,f=Array(2<d?d-2:0),h=2;h<d;h++)f[h-2]=arguments[h];return Object.entries(b).filter(function(a){return void 0!==M(a,2)[1]}).forEach(function(a){a=M(a,2);return c.setAttribute(a[0],a[1])}),Ga(f).forEach(function(a){return c.appendChild(function(a){return a instanceof Node?a.parentNode?a.cloneNode(!0):a:document.createTextNode(null==a?"":a)}(a))}),c}},{key:"dynamicInstance",value:function(a,b,c){var d,f=void 0;if("object"==("undefined"===
typeof c?"undefined":la(c))&&(f=(null===(d=c[b])||void 0===d?void 0:d.default)||c[b]),"function"==typeof c&&(f=c(b)),!f)throw Error("Unable to dynamically import "+a+":"+b);if("function"!=typeof f)throw Error("Expecting "+a+":"+b+" to be a method, but was: "+("undefined"===typeof f?"undefined":la(f)));return f}}]);return a}(ya));d=ta})();return d})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-pricing-utils-registration",function(g){g.when("pvw-constants").register("pvw-pricing-utils",
function(d){return{calculatePrice:function(d,f,g){d*=f;if(g)return{whole:Math.floor(d),fraction:0};g=Math.round(Math.round(d%1*1E4)/100);return{whole:Math.trunc(d)+Math.floor(g/100),fraction:g%100}},isNonFractionalCurrency:function(d){return"JPY"===d},formatPriceForDisplay:function(h,f,g,n,c){var p=5<arguments.length&&arguments[5]!==A?arguments[5]:d.PRECISION_DEFAULT,t="Left"===n;p=g?h.whole:parseFloat(h.whole+"."+h.fraction).toFixed(p);"."!==c&&c&&(p=p.replace(".",c));return t?""+f+p:""+p+f}}})});
"use strict";M=function(){return function(g,d){if(Array.isArray(g))return g;if(Symbol.iterator in Object(g)){var h=[],f=!0,t=!1,n=A;try{for(var c=g[Symbol.iterator](),p;!(f=(p=c.next()).done)&&(h.push(p.value),!d||h.length!==d);f=!0);}catch(z){t=!0,n=z}finally{try{if(!f&&c["return"])c["return"]()}finally{if(t)throw n;}}return h}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();x.when("PVWDuplicationGuard").execute("pvw-weight-utils-registration",function(g){g.when("pvw-constants").register("pvw-weight-utils",
function(d){function g(f,g){var h=2<arguments.length&&arguments[2]!==A?arguments[2]:d.PRECISION_DEFAULT,c=3<arguments.length&&arguments[3]!==A?arguments[3]:d.DECIMAL_SEPARATOR,p=M(g===d.UNITS.GRAM_SYMBOL&&1E3<=f?[f/1E3,d.UNITS.KILOGRAM_SYMBOL]:[f,g],2),t=p[0];p=p[1];return(c!==d.DECIMAL_SEPARATOR?t.toFixed(h).replace(d.DECIMAL_SEPARATOR,c):t.toFixed(h))+" "+p}return{calculateEstWeight:function(d,g,h){return h?(g*d).toFixed(2):d.toFixed(2)},getWeightUnitSymbol:function(f){return d.UNITS.UNIT_SYMBOL_MAP[f]||
d.UNITS.POUND_SYMBOL},formatWeightsForDisplay:function(f,h){var n=2<arguments.length&&arguments[2]!==A?arguments[2]:d.PRECISION_DEFAULT,c=3<arguments.length&&arguments[3]!==A?arguments[3]:d.DECIMAL_SEPARATOR;return f.map(function(d){return g(d,h,n,c)})},formatWeight:g}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-csm-util-registration",function(g){g.register("pvw-csm-util",function(){function d(d){v.ue&&v.ue.count&&d&&v.ue.count(d,(v.ue.count(d)||0)+1)}function g(d,c){return c?d+t.SUCCESS_COUNT:
d+t.FAILED_COUNT}function f(d,c){return c?d+":mobile":d+":desktop"}var t={INITIALIZE:"PortableVariableBottomSheet-Initialize",TRIGGER_ACTION:"PortableVariableBottomSheet-TriggerAction",SHOW_POPUP:"PortableVariableBottomSheet-ShowPopup",SUCCESS_COUNT:"-Success-Count",FAILED_COUNT:"-Failed-Count",HUNDREDTHS:"-Hundredths"};return{incrementTriggerDeclarativeActionCount:function(h,c,p){var n=t.TRIGGER_ACTION;n=g(n,c);n=f(n+":"+h,p);d(n)},incrementShowPopup:function(h,c){h=g(t.SHOW_POPUP,h);h=f(h,c);d(h)},
incrementInitializeCount:function(h,c){h=g(t.INITIALIZE,h);h=f(h,c);d(h)},logLatencyMetric:function(d,c,h){var g="PortableVariableBottomSheet-TimeTo"+t.HUNDREDTHS+d;d=f("PortableVariableBottomSheet-TimeTo"+d,h);g=f(g,h);v.ue&&v.ue.count&&d&&"undefined"!==typeof v.ue_t0&&(c-=v.ue_t0,v.ue.count(d,c),v.ue.count(g,Math.floor(c/10)))}}})});"use strict";x.when("PVWDuplicationGuard").execute("pvw-text-replace-registration",function(g){g.when("pvw-pricing-utils","pvw-weight-utils","pvw-constants","pvw-bs-translations").register("pvw-text-replace",
function(d,g,f,t){function h(c){return t.aboutUpperCase.replace(f.TEMPLATE_REPLACE_STRING.ESTIMATE,c)}function c(c,h){var q=0!==c&&c?c:h.sellingMin;if(h.isItemSoldByCount){c=g.calculateEstWeight(q,h.estimateAverageSize,h.isItemSoldByCount);var p=h.estimateAverageSizeUnitOfMeasureUnit?g.getWeightUnitSymbol(h.estimateAverageSizeUnitOfMeasureUnit):g.getWeightUnitSymbol(h.pricingUnitOfMeasureUnit);return g.formatWeight(Number(c),p,f.PRECISION_DEFAULT,h.decimalSeparator)}c=h.currencySymbol;p=d.isNonFractionalCurrency(h.pricePerUnitMoneyCurrencyCode);
q=d.calculatePrice(h.pricePerSingleUnitAmount,q,p);return d.formatPriceForDisplay(q,c,p,h.currencySymbolPosition||"Left",h.decimalSeparator)}function p(c,d){return"number"!==typeof c||0>c?(console.warn("Invalid quantity provided",c),!1):d?!0:!1}var v='\x3cspan class\x3d"a-text-bold"\x3e{replace}\x3c/span\x3e\x26nbsp\x3cspan\x3e'+t.variableWeightDisclaimer+"\x3c/span\x3e",x='\x3cspan class\x3d"a-text-bold"\x3e{replace}\x3c/span\x3e\x3cbr\x3e\x3cspan\x3e'+t.variableWeightDisclaimer+"\x3c/span\x3e";
return{replaceRegulatoryText:function(d,g,n){p(d,n)?(g=g.closest(f.PVW_CONTAINER).find(f.PVW_REPLACE),g||(console.warn("Unable to find target element for text replacement"),g=null),g?(d=c(d,n),d=h(d),d=v.replace(f.TEMPLATE_REPLACE_STRING.REPLACE,d),g={targetElement:g,htmlContent:d}):g=null):g=null;g&&g.targetElement.html(g.htmlContent)},generateAboutEstimationText:function(d,f){d=c(d,f);return h(d)},createRegulatoryDisplayDocumentFragment:function(d,g,n){if(!p(d,g))return null;d=c(d,g);n?(n=h(d),
n='\x3cspan class\x3d"a-text-bold"\x3e{replace}\x3c/span\x3e'.replace(f.TEMPLATE_REPLACE_STRING.REPLACE,n)):(n=h(d),n=x.replace(f.TEMPLATE_REPLACE_STRING.REPLACE,n));d=document.createDocumentFragment();g=document.createElement("div");g.innerHTML=n;d.appendChild(g);return d}}})});"use strict";x.declare("pvw-bs-translations",{summaryDisclaimerText:"The final price will be adjusted based on the actual weight of the items received.",quantitySelectorUnitText:"Item(s)",selectQuantityText:"Select quantity:",
estTotalPriceText:"Total est. price:",estTotalWeightText:"Total est.:",addToCartButtonText:"Add to Basket",updateCartButtonText:"Update cart",cancelMessage:"Cancel",aboutUpperCase:"About {estimate}.",aboutLowerCase:"(about {estimate})",variableWeightDisclaimer:"Final cost by weight.",updateQuantityText:"Update quantity",itemText:"{quantity} item",itemsText:"{quantity} items"})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("PortableOffersDisplayAssets@add-to-cart","PortableOffersDisplayAssets"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.register("pcta:add-to-cart:constants",function(){return{DECLARATIVE_ACTION_NAME:"cta-add-to-cart",METRICS:{AX_LOAD_TIME:"ax:load:time"},PREFIX:"items",ITEM_TYPES:{BASE:"base"},PARAMETER_PATHS:{QUANTITY:["quantity"],GIFTOPTIONS:["additionalParameters",
"giftOptions","includeGiftReceipt"],UOM_QUANTITY_DIMENSION:["unitOfMeasureQuantity","unitOfMeasure","dimension"],UOM_QUANTITY_UNIT:["unitOfMeasureQuantity","unitOfMeasure","unit"],UOM_QUANTITY_VALUE:["unitOfMeasureQuantity","value"]},ELEMENTS:{AX_ATC:".ax-atc",AX_FACEOUT_CONTAINER:".atc-faceout-container"},BUILD_TIME_CONSTANT:"build-change-v1"}});"use strict";a.when("A","pcta:add-to-cart:constants","cta-handler","pcta:utils:csm").register("pcta:add-to-cart:handler",function(b,a,c,f){b.declarative(a.DECLARATIVE_ACTION_NAME,
"click",function(a){c.handleCTAClick(a)});f.logPerformance(a.METRICS.AX_LOAD_TIME)});"use strict";a.when("A","pcta:add-to-cart:constants").register("pcta:atc-parameter-name",function(a,c){return{constructParameterName:function(a,b,d){if("string"===typeof a&&"number"===typeof b&&0<=b&&Array.isArray(d)){var e=c.PREFIX;e+="["+(b+"."+a)+"]";d.forEach(function(a){e+="["+a+"]"});return e}console.debug("pctaLogFatalsEvent","[Invalid parameters used to construct add to cart parameter]","WARN","addtocart_construct_parameter_error")}}})});
/* ******** */
(function(e){var m=window.AmazonUIPageJS||window.P,g=m._namespace||m.attributeErrors,c=g?g("PortableOffersDisplayAssets@variable-weight","PortableOffersDisplayAssets"):m;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,m,g){e.register("pcta:vw-constants",function(){return{DECLARATIVE_ACTIONS:{VW_PRE_ACTION:"pcta-pre-action-vw",VW_SPIN_BUTTON_CLICK:"a-stepper-spinbutton",VW_CHEVRON_CLICK:"a-stepper-chevron",VW_ATC_CLICK:"pvw-bs-atc-click"},ELEMENTS:{VW_PRE_ACTION:"[data-pcta-pre-action-vw]",
AX_VUOM:".ax-vuom"},PVW_BOTTOM_SHEET:"pvw_bottom_sheet",DIMENSION:{WEIGHT:"WEIGHT",COUNT:"COUNT"},UNITS:{UNIT:"UNIT"},EVENTS:{AX_ATC:"ax:atc",AX_QS_UPDATE:"ax:qs:update"}}});"use strict";e.when("A","ax:initiator","pcta:vw-constants","pcta:vw-util","pvw-drop-down","pvw-text-replace").register("pcta-preaction-vw-static",function(c,e,a,f,h,g){function k(d){var l=f.getMetaInfoForOpeningSheet(d);if(l){var a=d.$target.closest(".atc-faceout-container"),b=a.find("form"),p=a.find(".pvw-dropdown-container");
a=a.attr("data-asin");h.openDropdown(l,function(b){c.trigger("a:stepper:value:change",{$stepperElement:f.getStepperElement(d),newValue:b})},b,p,a)}}function n(d){var a=f.getMetaInfoForAxEvent(d);a&&g.replaceRegulatoryText(d.quantity,d.$faceoutContainer,a)}c.declarative(a.DECLARATIVE_ACTIONS.VW_PRE_ACTION,"click",function(a){a.$event.preventDefault();var c=a.$target.closest(".atc-faceout-container"),d=c.find("form"),b=c.find(".pvw-dropdown-container");c=c.attr("data-asin");h.openDropdown(a.data,function(b){b=
f.createRequestPayload(a,b);e.initiateCTAHandling(a,b)},d,b,c)});c.declarative(a.DECLARATIVE_ACTIONS.VW_CHEVRON_CLICK,"click",k);c.declarative(a.DECLARATIVE_ACTIONS.VW_SPIN_BUTTON_CLICK,"click",k);c.on(a.EVENTS.AX_ATC,function(a){n(a)});c.on(a.EVENTS.AX_QS_UPDATE,function(a){n(a)})});"use strict";e.when("A","a-stepper","pcta:vw-constants","pcta:add-to-cart:constants","pcta:atc-parameter-name","action-handler:dom-input-parser").register("pcta:vw-util",function(c,e,a,f,h,m){function k(b){b=b.find(a.ELEMENTS.AX_VUOM);
return 0<b.length?b.data().vuom:g}function n(b){b=b.find(a.ELEMENTS.VW_PRE_ACTION);return 0<b.length?b.data().pctaPreActionVw:g}function d(b){var a=b.siblings(f.ELEMENTS.AX_ATC),c=b.closest(f.ELEMENTS.AX_FACEOUT_CONTAINER);if(a=n(a)||k(c))b=e.getStepper(b),a.currentQuantity=b.getValue();return a}function l(b){return q(b.$event.currentTarget).closest("[data-a-component\x3dstepper]")}var q=c.$;return{getMetaInfoForOpeningSheet:function(b){b=l(b);return d(b)},getStepperElement:l,createRequestPayload:function(b,
c,d){var e=m.createRequestPayload(b);d=d||b&&b.data;b=d.isItemSoldByCount;d=d.sellingUnitOfMeasureUnit;var g=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.QUANTITY),p=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.UOM_QUANTITY_DIMENSION),k=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.UOM_QUANTITY_UNIT),l=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.UOM_QUANTITY_VALUE);e[g]=b?c:1;e[p]=b?a.DIMENSION.COUNT:a.DIMENSION.WEIGHT;e[k]=d||
a.UNITS.UNIT;e[l]=c;return e},getMetaInfoForAxEvent:function(b){var a=b.$faceoutContainer,c=a.find(f.ELEMENTS.AX_ATC);if(a=n(c)||k(a))a.currentQuantity=b.quantity;return a},getMetaInfoFromStepperElement:d}})});
/* ******** */
